name: ThirtySecondsToDie
version: '${project.version}'
main: dev.sasukector.thirtysecondstodie.ThirtySecondsToDie
api-version: 1.17
authors: [ Sasukector ]
description: This is the core plugin for ThirtySecondsToDie
website: https://sasukector.dev
commands:
  game:
    description: Command to manage the game
    usage: /game [option]
  options:
    description: Command to manage game options
    usage: /options [option] [suboption]